name: rapidval
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_ai: ^3.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_animate: ^4.5.0
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_markdown: ^0.7.4+1
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1
  google_sign_in: ^6.3.0
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.12.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  drift_dev: ^2.29.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/developer_image.png


scripts:
  generate: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs